os: linux
language: python

sudo: false
python:
 - "3.8"

install:
 - "pip install -r requirements.txt"
 - "pip install ."
 - "pip install setuptools"
 - "pip install pyinstaller"

script:
  - bash -c echo "Tests must go here"

before_deploy:
  - pyinstaller --onefile --paths kb/ kb/__main__.py -n kb

deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
